/**
 * Splitwise
 * API Design for Splitwise
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bivekkumar@promactinfo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SettlementDTO {
  id?: number;
  payeeName?: string;
  receiverName?: string;
  amount?: number;
}
